//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C__Yaml_Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C__Yaml_Parser.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS Yaml Parser.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FOLDER.
        /// </summary>
        internal static string BTN_ADD_FOLDER {
            get {
                return ResourceManager.GetString("BTN_ADD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        internal static string CHK_INCLUDE_SUBFOLDERS {
            get {
                return ResourceManager.GetString("CHK_INCLUDE_SUBFOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown and text.
        /// </summary>
        internal static string CHK_MD_AND_TEXT {
            get {
                return ResourceManager.GetString("CHK_MD_AND_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents:.
        /// </summary>
        internal static string LBL_CONTENTS {
            get {
                return ResourceManager.GetString("LBL_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        internal static string LBL_FILE_NAME {
            get {
                return ResourceManager.GetString("LBL_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        internal static string LBL_FOLDER {
            get {
                return ResourceManager.GetString("LBL_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language:.
        /// </summary>
        internal static string LBL_LANGUAGE {
            get {
                return ResourceManager.GetString("LBL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of files:.
        /// </summary>
        internal static string LBL_LIST_OF_FILES {
            get {
                return ResourceManager.GetString("LBL_LIST_OF_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string LBL_YAML_AUTHOR {
            get {
                return ResourceManager.GetString("LBL_YAML_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string LBL_YAML_BTN_CLEAR {
            get {
                return ResourceManager.GetString("LBL_YAML_BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULTS.
        /// </summary>
        internal static string LBL_YAML_BTN_DEFAULTS {
            get {
                return ResourceManager.GetString("LBL_YAML_BTN_DEFAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string LBL_YAML_CATEGORIES {
            get {
                return ResourceManager.GetString("LBL_YAML_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string LBL_YAML_DATE {
            get {
                return ResourceManager.GetString("LBL_YAML_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout:.
        /// </summary>
        internal static string LBL_YAML_LAYOUT {
            get {
                return ResourceManager.GetString("LBL_YAML_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string LBL_YAML_TITLE {
            get {
                return ResourceManager.GetString("LBL_YAML_TITLE", resourceCulture);
            }
        }
    }
}
